# Spring Boot application properties
spring:
  application:
    name: app-core

  # DataSource configuration for MySQL
  # Replace the following properties with your MySQL server details

  datasource:
    name: BaseDS
    url: jdbc:mysql://localhost:3306/app_core
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  # JPA (Java Persistence API) and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update # Use "update" to automatically update the schema, or change to "create" to recreate on every start (not recommended for production).
    show-sql: true # Set to true to enable SQL logging for debugging

    # Specify the package where your JPA entities are located
    # Change 'com.example' to the actual package of your entities
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  # Customize the entity scan base package
  base-packages: com.example

  jackson:
    date-format: yyyy/MM/dd HH:mm:ss z


# Server configuration
server:
  port: 8080

